#!/usr/bin/env zsh
#
# install and configure alacritty terminal
# https://github.com/alacritty/alacritty
#

set -eu
#set -o xtrace
# set `magic` variables for current file and dir
__dir="$(cd "$(dirname "$0")" && pwd)"
__file="${__dir}/$(basename "$0")"
__base="$(basename ${__file})"
__root="$(cd "$(dirname "${__dir}")" && pwd)"
source "$__root/script/functions"

UPD=0
BREW=0
FLAV="light"
while [ "${1-}" != "" ]; do
  case $1 in
    --update ) UPD=1 ;;
    --brew )  BREW=1 ;;
    --light ) FLAV="light" ;;
    --full )  FLAV="full" ;;
  esac
  shift
done

if [[ $FLAV != "full" ]]; then
  skip "Skipping alacritty installation because of variant ($FLAV)"
fi

info "Installing alacritty"

if [[ $DOT_KERNEL == "darwin" ]]; then
  # homebrew install, casks are supported only on macOS
  brew_cask_install alacritty
  [[ -d "$XDG_CONFIG_HOME/alacritty" ]] || mkdir "$XDG_CONFIG_HOME/alacritty"
  link_file "$DOTFILES/alacritty/Darwin.alacritty.yml" "$XDG_CONFIG_HOME/alacritty/alacritty.yml"
elif [[ $DOT_KERNEL == "linux" ]]; then
  # linux install
  warn "Not implemented for your platform"
else
  warn "Not implemented for your platform"
fi

success "Done"

