#!/usr/bin/env zsh
#
# install and configure kitty terminal
# https://sw.kovidgoyal.net/kitty/
#

set -eu
#set -o xtrace
# set `magic` variables for current file and dir
__dir="$(cd "$(dirname "$0")" && pwd)"
__file="${__dir}/$(basename "$0")"
__base="$(basename ${__file})"
__root="$(cd "$(dirname "${__dir}")" && pwd)"
source "$__root/script/functions"

UPD=0
BREW=0
FLAV="light"
while [ "${1-}" != "" ]; do
  case $1 in
    --update ) UPD=1 ;;
    --brew )  BREW=1 ;;
    --light ) FLAV="light" ;;
    --full )  FLAV="full" ;;
  esac
  shift
done

if [[ $FLAV != "full" ]]; then
  skip "Skipping kitty installation because of variant ($FLAV)"
  exit
fi

info "Installing kitty"

if [[ $DOT_KERNEL == "darwin" ]]; then
  # homebrew install, casks are supported only on macOS
  brew_cask_install kitty
  [[ -d "$XDG_CONFIG_HOME/kitty" ]] || mkdir "$XDG_CONFIG_HOME/kitty"
  link_file "$DOTFILES/kitty/kitty.conf" "$XDG_CONFIG_HOME/kitty/kitty.conf"

elif [[ $DOT_KERNEL == "linux" ]]; then
  # linux install
  warn "Not implemented for your platform"
else
  warn "Not implemented for your platform"
fi

success "Done"

