#!/usr/bin/env zsh
#
# configure git
#

set -eu
#set -o xtrace
# set `magic` variables for current file and dir
__dir="$(cd "$(dirname "$0")" && pwd)"
__file="${__dir}/$(basename "$0")"
__base="$(basename ${__file})"
__root="$(cd "$(dirname "${__dir}")" && pwd)"
source "$__root/script/functions"

UPD=0
BREW=0
FLAV="light"
while [ "${1-}" != "" ]; do
  case $1 in
    --update ) UPD=1 ;;
    --brew )  BREW=1 ;;
    --light ) FLAV="light" ;;
    --full )  FLAV="full" ;;
  esac
  shift
done

info "Installing  ($FLAV)"

link_file "$DOTFILES/git/.gitignore" "$HOME/.gitignore"
link_file "$DOTFILES/git/.gitconfig.local" "$HOME/.gitconfig.local"

if [[ $DOT_KERNEL == "darwin" ]]; then
  # macOS install
  git config --global credential.helper osxkeychain
elif [[ $DOT_KERNEL == "linux" ]]; then
  # linux install
  git config --global credential.helper 'cache --timeout 7200'
fi

success "Done"

