#!/usr/bin/env zsh
# installs some useful default settings on macos
#

set -eu
#set -o xtrace
# set `magic` variables for current file and dir
__dir="$(cd "$(dirname "$0")" && pwd)"
__file="${__dir}/$(basename "$0")"
__base="$(basename ${__file})"
__root="$(cd "$(dirname "${__dir}")" && pwd)"
source "$__root/script/functions"

UPD=0
BREW=0
FLAV="light"
while [ "${1-}" != "" ]; do
  case $1 in
    --update ) UPD=1 ;;
    --brew )  BREW=1 ;;
    --light ) FLAV="light" ;;
    --full )  FLAV="full" ;;
  esac
  shift
done

info "Installing macos settings ($FLAV)"

if [[ $DOT_KERNEL == "darwin" ]]; then
  # macOS install
  if [[ $FLAV == "full" ]]; then
    info "Setting some default values, we need privileges for that"
    warn "Prepare to enter your password"
    "$__dir/set-defaults"
  else
    skip "Skipped because of cariant: $FLAV"
  fi
elif [[ $DOT_KERNEL == "linux" ]]; then
  skip "Not needed for your platform"
else
  warn "Not implemented for your platform"
fi

success "Done"

