#!/usr/bin/env zsh
#
# fzf - command line fuzzy finder
# https://github.com/junegunn/fzf
#

set -eu
#set -o xtrace
# set `magic` variables for current file and dir
__dir="$(cd "$(dirname "$0")" && pwd)"
__file="${__dir}/$(basename "$0")"
__base="$(basename ${__file})"
__root="$(cd "$(dirname "${__dir}")" && pwd)"
source "$__root/script/functions"

UPD=0
BREW=0
FLAV="light"
while [ "${1-}" != "" ]; do
  case $1 in
    --update ) UPD=1 ;;
    --brew )  BREW=1 ;;
    --light ) FLAV="light" ;;
    --full )  FLAV="full" ;;
  esac
  shift
done

info "Installing  ($FLAV)"

if [[ $DOT_KERNEL == "darwin" ]] || [[ $BREW -eq 1 ]]; then
  # macOS install
  brew_install fzf
  $(brew --prefix)/opt/fzf/install --xdg --key-bindings --completion --no-bash --no-fish --no-update-rc
elif [[ $DOT_KERNEL == "linux" ]]; then
  # linux install
  if [[ -d "$XDG_DATA_HOME/fzf" ]]; then
    git -C "$XDG_DATA_HOME/fzf" pull
  else
    git clone --depth 1 https://github.com/junegunn/fzf.git "$XDG_DATA_HOME/fzf"
  fi
  "$XDG_DATA_HOME"/fzf/install --xdg --key-bindings --completion --no-bash --no-fish --no-update-rc
else
  warn "Not implemented for your platform"
fi

success "Done"

