#!/usr/bin/env zsh
#
# install bat - cat with wings
#

set -eu
#set -o xtrace
# set `magic` variables for current file and dir
__dir="$(cd "$(dirname "$0")" && pwd)"
__file="${__dir}/$(basename "$0")"
__base="$(basename ${__file})"
__root="$(cd "$(dirname "${__dir}")" && pwd)"
source "$__root/script/functions"

UPD=0
BREW=0
FLAV="light"
while [ "${1-}" != "" ]; do
  case $1 in
    --update ) UPD=1 ;;
    --brew )  BREW=1 ;;
    --light ) FLAV="light" ;;
    --full )  FLAV="full" ;;
  esac
  shift
done

info "Installing bat"

if [[ $DOT_KERNEL == "darwin" ]] || [[ $BREW -eq 1 ]]; then
  # macOS install
  brew_install bat
elif [[ $DOT_KERNEL == "linux" ]]; then
  # linux install
  if [[ $DOT_VARIANT == "arch" ]]; then
    linux_install bat
  else
    local url=$(curl -s https://api.github.com/repos/sharkdp/bat/releases/latest | \
      jq '.assets[] | select(.name | test("bat_(.+)_amd64.deb")) | .browser_download_url' | \
      sed 's/"//g')

    echo $url
    curl -Llo $XDG_RUNTIME_DIR/bat.deb $url
    sudo dpkg -i $XDG_RUNTIME_DIR/bat.deb
    rm -f $XDG_RUNTIME_DIR/bat.deb
  fi
else
  warn "Not implemented for your platform"
fi

success "Done"

