#!/usr/bin/env zsh
#
# install and configure go
#

set -eu
#set -o xtrace
# set `magic` variables for current file and dir
__dir="$(cd "$(dirname "$0")" && pwd)"
__file="${__dir}/$(basename "$0")"
__base="$(basename ${__file})"
__root="$(cd "$(dirname "${__dir}")" && pwd)"
source "$__root/script/functions"

UPD=0
BREW=0
FLAV="light"
while [ "${1-}" != "" ]; do
  case $1 in
    --update ) UPD=1 ;;
    --brew )  BREW=1 ;;
    --light ) FLAV="light" ;;
    --full )  FLAV="full" ;;
  esac
  shift
done

VERSION="1.14.6"
info "Installing go"

if [[ $DOT_KERNEL == "darwin" ]] || [[ $BREW -eq 1 ]]; then
  # macOS install
  brew_install go

  [[ -d "$XDG_CODE_HOME/go" ]] || mkdir -p "$XDG_CODE_HOME"/go/{src,bin,pkg}
elif [[ $DOT_KERNEL == "linux" ]]; then
  # linux install
  if [[ -n $(command -v go) ]]; then 
    INST_VER=$(go version | sed -r 's/(go version go)(.+) (.+)/\2/g')
    [[ $INST_VER == $VERSION ]] && skip "Go version: $INST_VER already installed" && exit 0
  fi

  curl -Llo "$XDG_RUNTIME_DIR/go$VERSION.linux.tar.gz" "https://golang.org/dl/go$VERSION.linux-amd64.tar.gz"
  sudo tar -xzf "$XDG_RUNTIME_DIR/go$VERSION.linux.tar.gz" -C "/usr/local"
  rm "$XDG_RUNTIME_DIR/go$VERSION.linux.tar.gz"

  [[ -d "$XDG_CODE_HOME/go" ]] || mkdir -p "$XDG_CODE_HOME"/go/{src,bin,pkg}
else
  warn "Not implemented for your platform"
fi

source "$__dir"/path.zsh
unset VERSION
success "Done"

